[package]
name = "adventurust"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["advanced"]}
priority-queue = "2.5.0"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.9.0"
